version: "3.7"
services:
  spark-master:
    image: bvilela/spark-master-hadoop:2.4.6
    container_name: spark-master
    hostname: spark-master
    tty: true
    volumes:
      - ./user_data:/user_data
    ports:
      - "8088:8088" # ResourceManager
      - "11070:50070" # NameNode WebUI
      - "10015:10015" # HDFS
      - "8080:8080" # WebUI Spark Master
      - "8042:8042" # NodeManager
      - "8888:8888" # Jupyter
      - "4040:4040" # Spark
      - "11000:10000" # HiveServer2 - Binary Mode
      - "11001:10001" # HiveServer - HTTP Mode
      - "11002:10002" # Hiveserver WebUI
      - "9092:9092" # Kafka
      - "9090:9090" #Nifi
    networks: 
      spark-network:
        ipv4_address: 192.168.0.17
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: bvilela/spark-worker-hadoop:2.4.6
    container_name: spark-worker-1
    hostname: spark-worker-1
    tty: true
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 192.168.0.17
  spark-worker-2:
    image: bvilela/spark-worker-hadoop:2.4.6
    container_name: spark-worker-2
    hostname: spark-worker-2
    tty: true
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 192.168.0.17
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
    